#!/usr/bin/env bash
#
# Project Initialization Wizard for expo-learning
# Generated by the /wizard skill using cesarchavezcal/agent-boilerplate
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=5

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you through initializing the expo-learning repository,\n' "$DIM"
  printf '  scaffolding the Expo stack, updating quad docs, and creating the setup PR.\n'
  printf '  Stop any time with Ctrl-C.%s\n\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" default_val="${3:-}" current input
  current=$(_existing "$key" || true)
  [[ -z "$current" && -n "$default_val" ]] && current="$default_val"
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Default: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Project Initialization Complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
  note "Project: expo-learning"
  note "Remote: https://github.com/cesarchavezcal/expo-learning"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Manual follow-ups:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  printf '  %sNext steps:%s\n' "$BOLD" "$RESET"
  printf '  1. Review the open Pull Request on GitHub\n'
  printf '  2. Run %snpx expo start%s to launch your mobile dev server\n\n' "$GREEN" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "expo-learning Project Initialization"

# ── Stage 1: GitHub Remote Setup ──────────────────────────────────────────
stage "GitHub Remote Setup"
say "Configuring GitHub repository and remotes under cesarchavezcal."

git config user.name "cesarchavezcal"
git config user.email "cesarchavezcal@gmail.com"
printf '  %s✓ git identity configured as cesarchavezcal%s\n' "$GREEN" "$RESET"

if ! git remote get-url origin >/dev/null 2>&1; then
  ask REPO_VISIBILITY "Repository visibility (public / private):" "public"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    step "Creating remote GitHub repo cesarchavezcal/expo-learning ($REPO_VISIBILITY)..."
    gh repo create "cesarchavezcal/expo-learning" "--$REPO_VISIBILITY" --source=. --remote=origin || {
      warn "Remote repository may already exist or need manual linking."
      git remote add origin "https://github.com/cesarchavezcal/expo-learning.git" || true
    }
  else
    warn "gh CLI not authenticated. Linking remote origin via HTTPS."
    git remote add origin "https://github.com/cesarchavezcal/expo-learning.git" || true
    SKIPPED+=("Create GitHub repo manually if not created: https://github.com/new")
  fi
else
  printf '  %s✓ Remote origin already configured: %s%s\n' "$GREEN" "$(git remote get-url origin)" "$RESET"
fi

pause "Press Enter to proceed to stack configuration..."

# ── Stage 2: Product & Stack Config ───────────────────────────────────────
stage "Product & Stack Configuration"
say "Define the domain and technical preferences for expo-learning."

ask PROJECT_DESC "One-sentence project description:" "Hands-on learning playground for React Native, Expo Router, and mobile architecture"
ask EXPO_TEMPLATE "Expo template flavor (tabs / blank-typescript):" "tabs"
ask PKG_MANAGER "Package manager (npm / bun / pnpm):" "npm"

printf '\n'
note "Selected Configuration:"
note "  - Description: $PROJECT_DESC"
note "  - Template: $EXPO_TEMPLATE"
note "  - Package Manager: $PKG_MANAGER"
printf '\n'

pause "Press Enter to begin scaffolding..."

# ── Stage 3: Scaffold Expo Codebase ───────────────────────────────────────
stage "Scaffold Expo Codebase"
say "Scaffolding Expo React Native project files into root directory."

if [ ! -f "package.json" ]; then
  step "Creating Expo app template in temporary workspace..."
  TEMP_EXPO_DIR=$(mktemp -d)
  
  if [ "$EXPO_TEMPLATE" = "tabs" ]; then
    npx create-expo-app@latest "$TEMP_EXPO_DIR" --template default --no-install
  else
    npx create-expo-app@latest "$TEMP_EXPO_DIR" --template blank-typescript --no-install
  fi

  step "Merging Expo files into project root..."
  rsync -av --exclude='.git' --exclude='README.md' "$TEMP_EXPO_DIR/" ./
  rm -rf "$TEMP_EXPO_DIR"

  step "Installing dependencies with $PKG_MANAGER..."
  if [ "$PKG_MANAGER" = "bun" ]; then
    bun install
  elif [ "$PKG_MANAGER" = "pnpm" ]; then
    pnpm install
  else
    npm install
  fi
  printf '  %s✓ Expo scaffolding and dependencies installed%s\n' "$GREEN" "$RESET"
else
  printf '  %s✓ package.json already exists. Skipping scaffolding.%s\n' "$GREEN" "$RESET"
fi

pause "Press Enter to update project documentation..."

# ── Stage 4: Populate Quad Files & Harness ─────────────────────────────────
stage "Populate Quad Files & Harness"
say "Replacing placeholders in CONTEXT.md, MEMORY.md, README.md, and init.sh."

# 1. CONTEXT.md
cat << 'EOF' > CONTEXT.md
# Project Context (`CONTEXT.md`)

This file holds the project's domain definition, architecture overview, and technology stack.

---

## 1. Project Overview

- **Project Name**: `expo-learning`
- **Domain / Description**: Hands-on learning playground for React Native, Expo Router, and mobile architecture patterns.
- **Target Audience / Mental Model**: Mobile developers exploring modern Expo SDK, file-based routing, native capabilities, and clean mobile architecture.

---

## 2. Technology Stack

- **Mobile Framework**: Expo (React Native, Expo Router)
- **Language & Runtime**: TypeScript, Node.js
- **State & UI**: React 19 / React Native Core + Expo vector icons
- **Testing Framework**: Jest / React Native Testing Library
- **Tooling & Linter**: ESLint, Prettier, Gentleman Guardian Angel (`.gga`)

---

## 3. Key Architecture & File Layout

```text
.
├── app/                    # Expo Router file-based routes and layouts
├── components/             # Reusable UI presentation and container components
├── constants/              # App themes, colors, and static configuration
├── hooks/                  # Custom React hooks
├── .atl/                   # Skill registry index
├── .gga                    # GGA AI code review configuration
├── AGENTS.md               # Operational rules & coding standards
├── CONTEXT.md              # Project domain definition & tech stack
├── MEMORY.md               # Architectural decision records
├── openspec/               # Spec-Driven Development specs & changes
└── docs/                   # Planning and product design documents
```

---

## 4. Key Conventions & Design System

- **Navigation**: File-based routing via `app/` directory (Expo Router).
- **Architecture**: Container-Presentational separation for screens and complex UI.
- **Type Safety**: Strict TypeScript without loose `any` casts.
EOF
printf '  %s✓ updated CONTEXT.md%s\n' "$GREEN" "$RESET"

# 2. MEMORY.md
cat << 'EOF' > MEMORY.md
# Agent Durable Memory (`MEMORY.md`)

This file records durable learnings, architectural decision records (ADRs), user preferences, and persistent project state across turns and agent sessions.

---

## 1. Architectural Decision Records (ADRs)

| Date | ADR Title | Decision & Rationale | Status |
|---|---|---|---|
| 2026-08-21 | ADR-001: Expo Router Stack Initialization | Adopt Expo with Expo Router file-based routing and strict TypeScript for structured mobile learning. | Accepted |

---

## 2. User Preferences & Standing Rules

- **Communication Style**: ADHD-optimised output style (`/i-have-adhd`). Lead with next action, number multi-step tasks, suppress tangents, and make progress visible.
- **Pipeline Governance**: Always run `/product-function` -> `/grill-with-docs` -> `/to-spec` -> `/information-architecture` -> `/ooux` -> `/to-tickets` -> `/implement`.
- **Git Commit Standard**: Verify local git configuration matches `cesarchavezcal` before committing.
EOF
printf '  %s✓ updated MEMORY.md%s\n' "$GREEN" "$RESET"

# 3. init.sh
cat << 'EOF' > init.sh
#!/bin/bash
set -e

echo "=== Harness Initialization: expo-learning ==="

if [ -f "package.json" ]; then
  echo "--> Running TypeScript type check..."
  npx tsc --noEmit || echo "⚠️ TypeScript check finished with notices."
fi

echo "=== Verification Complete ==="
echo ""
echo "Next steps:"
echo "1. Read feature_list.json to see current feature state"
echo "2. Pick ONE unfinished feature to work on"
echo "3. Implement only that feature"
echo "4. Re-run ./init.sh before claiming done"
EOF
chmod +x init.sh
printf '  %s✓ updated init.sh%s\n' "$GREEN" "$RESET"

# 4. Update openspec/config.yaml
cat << 'EOF' > openspec/config.yaml
# OpenSpec Configuration
schema: 1

project:
  name: expo-learning
  repository: cesarchavezcal/expo-learning
  type: mobile-app
  description: Hands-on learning playground for React Native, Expo Router, and mobile architecture patterns.
  stack:
    language: typescript
    frameworks:
      - react-native
      - expo
      - expo-router
    package_manager: npm
    build_tool: expo

testing:
  runner: jest
  framework: react-native-testing-library
  layers:
    - unit
    - component
  coverage_tool: null
  strict_tdd: true
  command: npm test

quality:
  linter: gga
  linter_config: .gga
  formatter: prettier
  type_checker: tsc

conventions:
  git:
    branch_pattern: "{prefix}/CCH/{project-initials}-{ticket-number}-{ticket-summary}"
    commit_pattern: "<prefix>(<scope>): <summary>"
    pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
  pipeline:
    explore:
      command: "/product-function"
      secondary: "/grill-with-docs"
    spec:
      command: "/to-spec"
    design:
      command: "/information-architecture"
      secondary: "/ooux"
    tasks:
      command: "/to-tickets"
    apply:
      executor: "/implement"
      worker: "/harness"
      swarm: "/team-cheap"
    verify:
      review: "/code-review"
      gate: ".gga"
    archive:
      command: "/sdd-archive"

skills:
  registry_path: ".atl/skill-registry.md"
  lockfile_path: "skills-lock.json"
  count: 42
  global_count: 25
  total_ecosystem_count: 67

persistence:
  mode: openspec
EOF
printf '  %s✓ updated openspec/config.yaml%s\n' "$GREEN" "$RESET"

pause "Press Enter to create the initial setup branch and PR..."

# ── Stage 5: Initial Setup Branch & PR ────────────────────────────────────
stage "Initial Setup Branch & Pull Request"
say "Creating initial setup branch and opening Pull Request."

BRANCH_NAME="chore/CCH/initial-setup-project-context"
step "Checking out branch $BRANCH_NAME..."
git checkout -B "$BRANCH_NAME"

step "Staging and committing files..."
git add .
git commit -m "chore(setup): initialize project context, expo stack scaffolding, and skill registry" || true

if git remote get-url origin >/dev/null 2>&1; then
  step "Pushing branch to origin..."
  git push -u origin "$BRANCH_NAME" || warn "Could not push to origin automatically."

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    step "Opening GitHub Pull Request..."
    gh pr create \
      --title "chore(setup): initialize project context and expo stack" \
      --body "Initializes expo-learning project quad files, scaffolds Expo React Native stack, and sets up SDD skill registry." \
      --label "chore" || warn "Pull Request already exists or could not be created automatically."
  fi
fi

finish
